export const GIRLS = [
    { company: "8D Creative",           name: "KANG HYEWON",        img: 'https://imgur.com/XT3YpTK.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "A team",                name: "KIM CHOYEON",        img: 'https://imgur.com/0AEGH7w.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "AKB48",                 name: "ASAI NANAMI",        img: 'https://imgur.com/bClevmB.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "AKB48",                 name: "CHIBA ERII",         img: 'https://imgur.com/hThWSVH.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "AKB48",                 name: "GOTO MOE",           img: 'https://imgur.com/cGj0jc6.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "AKB48",                 name: "HONDA HITOMI",       img: 'https://imgur.com/7MfqvTt.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "AKB48",                 name: "ICHIKAWA MANAMI",    img: 'https://imgur.com/9Ej5LQG.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "AKB48",                 name: "IWATATE SAHO",       img: 'https://imgur.com/C8HKlhw.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "AKB48",                 name: "KOJIMA MAKO",        img: 'https://imgur.com/VVkEja6.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "AKB48",                 name: "MIYAZAKI MIHO",      img: 'https://imgur.com/lY2LyQR.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "AKB48",                 name: "MOGI SHINOBU",       img: 'https://imgur.com/9CwkBO7.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "AKB48",                 name: "MUTO TOMU",          img: 'https://imgur.com/29cKhAz.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "AKB48",                 name: "NAKANISHI CHIYORI",  img: 'https://imgur.com/7DrV50i.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "AKB48",                 name: "NAKANO IKUMI",       img: 'https://imgur.com/304cwS3.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "AKB48",                 name: "NAGANO SERIKA",      img: 'https://imgur.com/ou9MKar.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "AKB48",                 name: "ODA ERINA",          img: 'https://imgur.com/uqlVWbG.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "AKB48",                 name: "SATO MINAMI",        img: 'https://imgur.com/xdLJRK1.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "AKB48",                 name: "SHINOZAKI AYANA",    img: 'https://imgur.com/GfHrdWz.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "AKB48",                 name: "SHITAO MIU",         img: 'https://imgur.com/wJqVLdz.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "AKB48",                 name: "TAKAHASHI JURI",     img: 'https://imgur.com/tSvuRsK.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "AKB48",                 name: "TAKEUCHI MIYU",      img: 'https://imgur.com/gnWRPkv.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Banana Culture",        name: "KIM DAHYE",          img: 'https://imgur.com/g0kOqV8.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "Banana Culture",        name: "KIM NAYOUNG",        img: 'https://imgur.com/zsqRCOg.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Blockberry",            name: "KO YUJIN",           img: 'https://imgur.com/ELvIjO5.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "CNC",                   name: "HONG YEJI",          img: 'https://imgur.com/rDHmoQ5.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "CNC",                   name: "KIM DAYEON",         img: 'https://imgur.com/EussV8p.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "CNC",                   name: "KIM YUBIN",          img: 'https://imgur.com/VmIE33t.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "CNC",                   name: "LEE YUJEONG",        img: 'https://imgur.com/OnHdek7.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "CNC",                   name: "YOON EUNBIN",        img: 'https://imgur.com/vhpw8wf.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "Collazoo Company",      name: "KIM HYUNAH",         img: 'https://imgur.com/PuxhqSX.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "CUBE",                  name: "HAN CHOWON",         img: 'https://imgur.com/NbisEeK.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "FAVE",                  name: "SHIN SUHYUN",        img: 'https://imgur.com/ERL5zcb.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "FENT",                  name: "KIM DOAH",           img: 'https://imgur.com/S32IX0T.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "FNC",                   name: "CHO AHYEONG",        img: 'https://imgur.com/sqapsYE.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "FNC",                   name: "PARK HAEYOON",       img: 'https://imgur.com/t0TfB1c.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "HKT48",                 name: "ARAMAKI MISAKI",     img: 'https://imgur.com/tDKZNV5.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "HKT48",                 name: "IMADA MINA",         img: 'https://imgur.com/rcuKSEo.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "HKT48",                 name: "KURIHARA SAE",       img: 'https://imgur.com/8Gqtuu0.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "HKT48",                 name: "MATSUOKA NATSUMI",   img: 'https://imgur.com/VqlFMDY.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "HKT48",                 name: "MIYAWAKI SAKURA",    img: 'https://imgur.com/NMAxWBc.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "HKT48",                 name: "MOTOMURA AOI",       img: 'https://imgur.com/DZ9qw1W.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "HKT48",                 name: "MURAKAWA VIVIAN",    img: 'https://imgur.com/DjJ4lkn.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "HKT48",                 name: "TANAKA MIKU",        img: 'https://imgur.com/W3Q25XU.jpg',   left: true,     elim1: false,   elim2: false },
    { company: "HKT48",                 name: "TSUKIASHI AMANE",    img: 'https://imgur.com/R4LQavR.jpg',   left: true,     elim1: false,   elim2: false },
    { company: "HKT48",                 name: "YABUKI NAKO",        img: 'https://imgur.com/OU3kDdZ.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "HOW",                   name: "KIM MINSEO",         img: 'https://imgur.com/np2lJ2A.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "HOW",                   name: "WANG KE",            img: 'https://imgur.com/erfIJi5.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "HOW",                   name: "YU MINYOUNG",        img: 'https://imgur.com/hURpxJK.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "Individual Trainee",    name: "PARK JINNY",         img: 'https://imgur.com/iYNBu14.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "Individual Trainee",    name: "PARK SEOYOUNG",      img: 'https://imgur.com/WOtAl2G.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "Million Market",        name: "CHO SARANG",         img: 'https://imgur.com/N4D1Pdz.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "Million Market",        name: "SON EUNCHAE",        img: 'https://imgur.com/PJjEUoN.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "MMO",                   name: "WON SEOYEON",        img: 'https://imgur.com/2tFFz84.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "M&D17",                 name: "LEE CHAEJEONG",      img: 'https://imgur.com/tY2P9aA.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "M&D17",                 name: "PARK CHANJU",        img: 'https://imgur.com/neJXHjC.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "M&D17",                 name: "PARK MINJI",         img: 'https://imgur.com/h0eztCu.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "MNH",                   name: "LEE HAEUN",          img: 'https://imgur.com/kp0IqSZ.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "Music Works",           name: "CHOI SOEUN",         img: 'https://imgur.com/QNvCsl3.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "Music Works",           name: "YOON HAESOL",        img: 'https://imgur.com/qBG3Uw1.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "NGT48",                 name: "HASEGAWA RENA",      img: 'https://imgur.com/uhS95hN.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "NGT48",                 name: "YAMADA NOE",         img: 'https://imgur.com/NFrTiLl.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "NMB48",                 name: "KATO YUUKA",         img: 'https://imgur.com/X8fRS29.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "NMB48",                 name: "MURASE SAE",         img: 'https://imgur.com/Q15fd7A.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "NMB48",                 name: "NAIKI KOKORO",       img: 'https://imgur.com/vIr5ZpM.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "NMB48",                 name: "SHIROMA MIRU",       img: 'https://imgur.com/rIHIJNy.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "NMB48",                 name: "UEMURA AZUSA",       img: 'https://imgur.com/gqLTw0Y.jpg',   left: true,     elim1: false,   elim2: false },
    { company: "NMB48",                 name: "UMEYAMA COCONA",     img: 'https://imgur.com/kyOGQ27.jpg',   left: true,     elim1: false,   elim2: false },
    { company: "Pledis",                name: "HUH YUNJIN",         img: 'https://imgur.com/b5IfyDP.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Pledis",                name: "LEE GAEUN",          img: 'https://imgur.com/VgHm7cf.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "RBW",                   name: "NA GOEUN",           img: 'https://imgur.com/tqxs3dQ.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "RBW",                   name: "PARK JIEUN",         img: 'https://imgur.com/UYJlLRM.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "SKE48",                 name: "ASAI YUKA",          img: 'https://imgur.com/qvnT6aD.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "SKE48",                 name: "MATSUI JURINA",      img: 'https://imgur.com/qAM5ehq.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "Starship",              name: "AN YUJIN",           img: 'https://imgur.com/zp4gck6.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Starship",              name: "CHO KAHYEON",        img: 'https://imgur.com/cHyEwDp.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "Starship",              name: "JANG WONYOUNG",      img: 'https://imgur.com/xAqcmp3.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Stone Music",           name: "BAE EUNYEONG",       img: 'https://imgur.com/UcbN57w.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "Stone Music",           name: "JANG GYURI",         img: 'https://imgur.com/zDTXlat.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Stone Music",           name: "JO YURI",            img: 'https://imgur.com/SZsIWu5.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Stone Music",           name: "LEE SIAN",           img: 'https://imgur.com/AthXghr.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Urban Works",           name: "KIM MINJU",          img: 'https://imgur.com/TXMiVFU.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Wellmade Yedang",       name: "HWANG SOYEON",       img: 'https://imgur.com/ZLYUFFK.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "Wellmade Yedang",       name: "KANG DAMIN",         img: 'https://imgur.com/4Dp4bQJ.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "WM",                    name: "CHO YEONGIN",        img: 'https://imgur.com/kY7JWci.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "WM",                    name: "LEE CHAEYEON",       img: 'https://imgur.com/AyJhkLz.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "WM",                    name: "LEE SEUNGHYEON",     img: 'https://imgur.com/WKKdeVZ.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "Woollim",               name: "KIM CHAEWON",        img: 'https://imgur.com/QwtF57a.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Woollim",               name: "KIM SOHEE",          img: 'https://imgur.com/v6ZEdH8.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "Woollim",               name: "KIM SUYUN",          img: 'https://imgur.com/cXpRnE4.jpg',   left: false,    elim1: false,   elim2: true  },
    { company: "Woollim",               name: "KWON EUNBI",         img: 'https://imgur.com/Cfy5fnC.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "YGK+",                  name: "AHN YEWON",          img: 'https://imgur.com/XAxHCqY.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "YGK+",                  name: "CHOI YEONSOO",       img: 'https://imgur.com/YU95kbc.jpg',   left: false,    elim1: true,    elim2: true  },
    { company: "Yuehua",                name: "KIM SIHYEON",        img: 'https://imgur.com/dNByvtH.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Yuehua",                name: "WANG YIREN",         img: 'https://imgur.com/4fvdoNm.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "Yuehua",                name: "CHOI YENA",          img: 'https://imgur.com/gb3cwmS.jpg',   left: false,    elim1: false,   elim2: false },
    { company: "ZB Label",              name: "ALEX CHRISTINE",     img: 'https://imgur.com/3IzRm53.jpg',   left: false,    elim1: true,    elim2: true  }
]